In [1]:
## Nobite Analytics
#monday 7.09.2026:

In [3]:
#first step looking at umsatzstatistik jan 2026
import pandas as pd 
import os

In [4]:
df_sales = pd.read_excel("data/raw/sales_2026/Umsatzstatistik Tropical Concept 31.01.2026.xlsx")

In [5]:
df_sales.head()

,Versanddatum,Auftragsart,Qualifier,Beschreibung,Auftrag,Auftraggeber,BestellNr.,Kundengrupp,Name,Strasse,PLZ,Ort,Artikel,PZN,Bezeichnung,Liefermenge,Umsatz,Empfangszeit,Sendung
0,2026-01-02,Normalauftrag,Auftragsposition,Verkauf,615752,2158,3383,Pharma Pri,Richard Kehr GmbH & Co. KG,Sudetenstraﬂe 8,38114,Braunschweig,7338535,7338535,NOBITE Hautspray 100 ml,36,299.52,2025-12-30 12:30:28,9614926
1,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615885,568211765,56141,ANZAG,Alliance Healthcare Deutschland GmbH Niederlas...,Plauener Str. 161,13053,Berlin,325707,325707,NOBITE Kleidung Spray 100 ml,24,199.68,2026-01-02 10:26:34,9616810
2,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615982,2180,91536,PHOENIX,PHOENIX Pharmahandel GmbH & Co. KG Vertriebsze...,Am Kindleber Feld 3,99867,Gotha,7338535,7338535,NOBITE Hautspray 100 ml,12,99.84,2026-01-02 12:02:30,9617516
3,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615969,2155,81548,PHOENIX,PHOENIX Pharmahandel GmbH & Co. KG Vertriebsze...,Lengeder Straﬂe 42,13407,Berlin,325707,325707,NOBITE Kleidung Spray 100 ml,12,99.84,2026-01-02 12:01:52,9617495
4,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615862,2227,49965,PHOENIX,PHOENIX Pharmahandel GmbH & Co. KG Vertriebsze...,Schurwaldstraﬂe 14-16,73765,Neuhausen,325707,325707,NOBITE Kleidung Spray 100 ml,12,99.84,2026-01-02 10:12:14,9616702

In [6]:
df_sales.shape

(436, 19)

In [7]:
type(df_sales)

pandas.DataFrame

In [8]:
df_sales.columns

Index(['Versanddatum', 'Auftragsart', 'Qualifier', 'Beschreibung', 'Auftrag',
       'Auftraggeber', 'BestellNr.', 'Kundengrupp', 'Name', 'Strasse', 'PLZ',
       'Ort', 'Artikel', 'PZN', 'Bezeichnung', 'Liefermenge', 'Umsatz',
       'Empfangszeit', 'Sendung'],
      dtype='str')

In [9]:
df_sales.dtypes

Versanddatum    datetime64[us]
Auftragsart                str
Qualifier                  str
Beschreibung               str
Auftrag                  int64
Auftraggeber             int64
BestellNr.              object
Kundengrupp                str
Name                       str
Strasse                    str
PLZ                      int64
Ort                        str
Artikel                  int64
PZN                      int64
Bezeichnung                str
Liefermenge              int64
Umsatz                 float64
Empfangszeit    datetime64[us]
Sendung                  int64
dtype: object

In [10]:
df_sales.isna().sum()

Versanddatum    0
Auftragsart     0
Qualifier       0
Beschreibung    0
Auftrag         0
Auftraggeber    0
BestellNr.      0
Kundengrupp     0
Name            0
Strasse         0
PLZ             0
Ort             0
Artikel         0
PZN             0
Bezeichnung     0
Liefermenge     0
Umsatz          0
Empfangszeit    0
Sendung         0
dtype: int64

In [11]:
df_sales[['Auftragsart', 'Qualifier', 'Beschreibung']].drop_duplicates()

     Auftragsart         Qualifier Beschreibung
0  Normalauftrag  Auftragsposition      Verkauf

In [12]:
df_sales[['Artikel', 'PZN', 'Bezeichnung']].drop_duplicates()

      Artikel       PZN                                Bezeichnung
0     7338535   7338535                    NOBITE Hautspray 100 ml
1      325707    325707               NOBITE Kleidung Spray 100 ml
5     4436102   4436102        NOBITE Kleidung Spr¸hflasche 200 ml
22    7392210   7392210  NOBITE Haut Sensitive Spr¸hflasche 100 ml
38    4259189   4259189             NOBITE Verd¸nner Flasche 100ml
191  18020055  18020055                          NOBITE Kids 100ml

In [13]:
(df_sales['Artikel'] == df_sales['PZN']).all()

np.True_

In [14]:
df_sales['PLZ'].astype(str).str.len().value_counts()

PLZ
5    389
4     47
Name: count, dtype: int64

In [15]:
df_sales[df_sales['PLZ'].astype(str).str.len() == 4]['PLZ'].unique()[:10]

array([6193, 4349, 3042, 9116, 4425, 1109, 8393, 9661])

In [17]:
#looking if text and numbers are mixed 
df_sales['BestellNr.'].apply(type).value_counts()

BestellNr.
<class 'int'>    357
<class 'str'>     79
Name: count, dtype: int64

In [19]:
#if bestellnr is unique
df_sales['BestellNr.'].nunique()

269

In [21]:
df_sales[df_sales['BestellNr.'].duplicated(keep=False)].head(10)

,Versanddatum,Auftragsart,Qualifier,Beschreibung,Auftrag,Auftraggeber,BestellNr.,Kundengrupp,Name,Strasse,PLZ,Ort,Artikel,PZN,Bezeichnung,Liefermenge,Umsatz,Empfangszeit,Sendung
6,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615972,2205,73410,PHOENIX,PHOENIX Pharmahandel GmbH & Co. KG Vertriebsze...,Kirschbaumweg 23,50996,Kˆln,325707,325707,NOBITE Kleidung Spray 100 ml,48,399.36,2026-01-02 12:01:57,9617497
8,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615972,2205,73410,PHOENIX,PHOENIX Pharmahandel GmbH & Co. KG Vertriebsze...,Kirschbaumweg 23,50996,Kˆln,7338535,7338535,NOBITE Hautspray 100 ml,108,898.56,2026-01-02 12:01:57,9617497
9,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615985,20073,1498095,Sanacorp,Leopold Fiebig GmbH & Co. KG,Messering 1,76287,Rheinstetten,4436102,4436102,NOBITE Kleidung Spr¸hflasche 200 ml,6,63.30,2026-01-02 12:10:04,9617564
11,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615802,2193,H14169,Noweda,NOWEDA Arzneimittel AG Niederlassung Bielefel...,Einsteinstraﬂe 2,32052,Herford,7338535,7338535,NOBITE Hautspray 100 ml,12,99.84,2026-01-02 09:34:35,9616413
14,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615802,2193,H14169,Noweda,NOWEDA Arzneimittel AG Niederlassung Bielefel...,Einsteinstraﬂe 2,32052,Herford,325707,325707,NOBITE Kleidung Spray 100 ml,12,99.84,2026-01-02 09:34:35,9616413
19,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615985,20073,1498095,Sanacorp,Leopold Fiebig GmbH & Co. KG,Messering 1,76287,Rheinstetten,7338535,7338535,NOBITE Hautspray 100 ml,36,299.52,2026-01-02 12:10:04,9617564
21,2026-01-06,Normalauftrag,Auftragsposition,Verkauf,616255,2187,82617240,Sanacorp,Sanacorp Pharmahandel GmbH Niederlassung Hamburg,Marlowring 23-25,22525,Hamburg,7338535,7338535,NOBITE Hautspray 100 ml,36,299.52,2026-01-05 13:33:52,9622138
23,2026-01-06,Normalauftrag,Auftragsposition,Verkauf,616253,2190,62599203,Sanacorp,Sanacorp Pharmahandel GmbH Niederlassung Lange...,In den Kolkwiesen 74-78,30851,Langenhagen,7338535,7338535,NOBITE Hautspray 100 ml,96,798.72,2026-01-05 13:33:52,9622132
24,2026-01-06,Normalauftrag,Auftragsposition,Verkauf,616257,2178,122555062,Sanacorp,Sanacorp Pharmahandel GmbH Niederlassung F¸rth,Am Weidiggraben 14,90763,F¸rth,7338535,7338535,NOBITE Hautspray 100 ml,48,399.36,2026-01-05 13:33:52,9622144
26,2026-01-06,Normalauftrag,Auftragsposition,Verkauf,616257,2178,122555062,Sanacorp,Sanacorp Pharmahandel GmbH Niederlassung F¸rth,Am Weidiggraben 14,90763,F¸rth,4436102,4436102,NOBITE Kleidung Spr¸hflasche 200 ml,12,126.60,2026-01-05 13:33:52,9622144

In [22]:
df_sales['Kundengrupp'].value_counts()

Kundengrupp
ANZAG         127
PHOENIX       105
Sanacorp       86
Noweda         69
TC Privat      26
Pharma Pri     21
AEP             2
Name: count, dtype: int64

In [23]:
df_sales[['Liefermenge', 'Umsatz']].describe()

       Liefermenge       Umsatz
count   436.000000   436.000000
mean     51.740826   458.655321
std      82.938001   736.123782
min       6.000000    49.920000
25%      12.000000    99.840000
50%      24.000000   199.680000
75%      60.000000   499.200000
max     924.000000  7687.680000

In [24]:
df_sales[['Liefermenge', 'Umsatz']].sum()

Liefermenge     22559.00
Umsatz         199973.72
dtype: float64

In [25]:
df_sales['Versanddatum'].min(), df_sales['Versanddatum'].max()

(Timestamp('2026-01-02 00:00:00'), Timestamp('2026-01-30 00:00:00'))

In [26]:
#exploring lagerliste jan 2026:
df_inventory = pd.read_excel("data/raw/inventory_2026/LagerlisteTropical-2026-01-31.xlsx")

In [27]:
df_inventory.head()

,PZN,ArtikelNr,Bezeichnung,WEDatum,Charge,Verfalldatum,Status,Anfangsbestand,Zugang,Abgang,...,sonstige Vernichtung,Inventuren,Vernichtung R¸-Mu,Bruch SK,Vernichtung Retouren,Verdeckter Bruch WE,R¸-Mu,Verdeckter Bruch,Sonstige,Endbestand
0,NaN,325707,NOBITE Kleidung Spray 100 ml,2021-06-22,21013233,2025-09-30,4,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1,NaN,325707,NOBITE Kleidung Spray 100 ml,2023-03-10,22017398,2025-10-31,4,14,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
2,NaN,325707,NOBITE Kleidung Spray 100 ml,2024-07-18,24020137,2029-06-30,4,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,NaN,325707,NOBITE Kleidung Spray 100 ml,2025-02-19,25020897,2028-01-31,2,3258,3360.0,-2647.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3971
4,NaN,4259189,NOBITE Verd¸nner Flasche 100ml,2023-08-04,22017249,2027-08-31,4,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3

In [28]:
df_inventory.shape

(25, 22)

In [30]:
df_inventory.columns

Index(['PZN', 'ArtikelNr', 'Bezeichnung', 'WEDatum', 'Charge', 'Verfalldatum',
       'Status', 'Anfangsbestand', 'Zugang', 'Abgang', 'Retouren',
       'Abgang an Konfektionierung', 'sonstige Vernichtung', 'Inventuren',
       'Vernichtung R¸-Mu', 'Bruch SK', 'Vernichtung Retouren',
       'Verdeckter Bruch WE', 'R¸-Mu', 'Verdeckter Bruch', 'Sonstige',
       'Endbestand'],
      dtype='str')

In [31]:
df_inventory.dtypes

PZN                                  float64
ArtikelNr                              int64
Bezeichnung                              str
WEDatum                       datetime64[us]
Charge                                object
Verfalldatum                  datetime64[us]
Status                                 int64
Anfangsbestand                         int64
Zugang                               float64
Abgang                               float64
Retouren                             float64
Abgang an Konfektionierung           float64
sonstige Vernichtung                 float64
Inventuren                           float64
Vernichtung R¸-Mu                    float64
Bruch SK                             float64
Vernichtung Retouren                 float64
Verdeckter Bruch WE                  float64
R¸-Mu                                float64
Verdeckter Bruch                     float64
Sonstige                             float64
Endbestand                             int64
dtype: object

In [32]:
df_inventory.isna().sum()

PZN                           25
ArtikelNr                      0
Bezeichnung                    0
WEDatum                        0
Charge                         0
Verfalldatum                   0
Status                         0
Anfangsbestand                 0
Zugang                        21
Abgang                        17
Retouren                      24
Abgang an Konfektionierung    25
sonstige Vernichtung          24
Inventuren                    25
Vernichtung R¸-Mu             25
Bruch SK                      25
Vernichtung Retouren          25
Verdeckter Bruch WE           25
R¸-Mu                         25
Verdeckter Bruch              25
Sonstige                      25
Endbestand                     0
dtype: int64

In [33]:
df_inventory[['ArtikelNr', 'Bezeichnung', 'Charge']].drop_duplicates()

    ArtikelNr                                Bezeichnung    Charge
0      325707               NOBITE Kleidung Spray 100 ml  21013233
1      325707               NOBITE Kleidung Spray 100 ml  22017398
2      325707               NOBITE Kleidung Spray 100 ml  24020137
3      325707               NOBITE Kleidung Spray 100 ml  25020897
4     4259189             NOBITE Verd¸nner Flasche 100ml  22017249
5     4259189             NOBITE Verd¸nner Flasche 100ml  23018705
6     4436102        NOBITE Kleidung Spr¸hflasche 200 ml  22017077
7     4436102        NOBITE Kleidung Spr¸hflasche 200 ml  23018829
9     4436102        NOBITE Kleidung Spr¸hflasche 200 ml  23018830
10    4436102        NOBITE Kleidung Spr¸hflasche 200 ml  24020633
11    4436102        NOBITE Kleidung Spr¸hflasche 200 ml  25021475
12    7338535                    NOBITE Hautspray 100 ml     14998
13    7338535                    NOBITE Hautspray 100 ml     17545
14    7338535                    NOBITE Hautspray 100 ml     17843
15    7338535                    NOBITE Hautspray 100 ml     17844
16    7338535                    NOBITE Hautspray 100 ml     19892
17    7338535                    NOBITE Hautspray 100 ml     20650
18    7338535                    NOBITE Hautspray 100 ml     20651
21    7338535                    NOBITE Hautspray 100 ml  020652/B
22    7392210  NOBITE Haut Sensitive Spr¸hflasche 100 ml  25021015
23   18020055                          NOBITE Kids 100ml    424126
24   18020055                          NOBITE Kids 100ml    102541

In [35]:
#Die Produkt-IDs in Sales (Artikel) und Inventory (ArtikelNr) stimmen für Januar 2026 vollständig überein
set(df_sales['Artikel'].unique()) == set(df_inventory['ArtikelNr'].unique())

True

In [36]:
#Abgang vs. Liefermenge = gleich 
df_inventory['Abgang'].sum(), df_sales['Liefermenge'].sum()

(np.float64(-22559.0), np.int64(22559))

In [37]:
#Abgang vs. Liefermenge pro product = gleich 
sales_by_product = df_sales.groupby('Artikel')['Liefermenge'].sum()
inventory_by_product = df_inventory.groupby('ArtikelNr')['Abgang'].sum().abs()

sales_by_product, inventory_by_product

(Artikel
 325707       2647
 4259189       804
 4436102      4704
 7338535     11572
 7392210      2316
 18020055      516
 Name: Liefermenge, dtype: int64,
 ArtikelNr
 325707       2647.0
 4259189       804.0
 4436102      4704.0
 7338535     11572.0
 7392210      2316.0
 18020055      516.0
 Name: Abgang, dtype: float64)

In [38]:
df_inventory.groupby('ArtikelNr')['Endbestand'].sum()

ArtikelNr
325707       3988
4259189       742
4436102      8548
7338535     12057
7392210      2418
18020055     1669
Name: Endbestand, dtype: int64

In [40]:
#um statuscodes zu kennen -> wissen nicht was es bedeutet 
df_inventory['Status'].value_counts()

Status
4     11
2      9
1      4
70     1
Name: count, dtype: int64

In [41]:
#Postleitzahl:
df_plz = pd.read_excel("data/reference/Liste-der-PLZ-in-Excel-Karte-Deutschland-Postleitzahlen.xlsx")

In [42]:
df_plz.head()

    PLZ Bundesland    Kreis    Typ
0  1067    Sachsen  Dresden  Stadt
1  1069    Sachsen  Dresden  Stadt
2  1097    Sachsen  Dresden  Stadt
3  1099    Sachsen  Dresden  Stadt
4  1108    Sachsen  Dresden  Stadt

In [43]:
df_plz.shape

(8196, 4)

In [44]:
df_plz.columns

Index(['PLZ', 'Bundesland', 'Kreis', 'Typ'], dtype='str')

In [45]:
df_plz.dtypes

PLZ           int64
Bundesland      str
Kreis           str
Typ             str
dtype: object

In [46]:
df_plz.isna().sum()

PLZ           0
Bundesland    0
Kreis         0
Typ           0
dtype: int64

In [48]:
df_sales['PLZ'].isin(df_plz['PLZ']).value_counts()

PLZ
True    436
Name: count, dtype: int64

In [50]:
#Cleaning sales: 
#SALES
#1. PLZ → String + 5 Stellen
#2. BestellNr. → String
#3. Artikel → String
#4. PZN → String
#5. Dates checken

In [51]:
sales_clean = df_sales.copy()

In [53]:
#plz clean:
sales_clean['PLZ'] = sales_clean['PLZ'].astype(str).str.zfill(5)
sales_clean['PLZ'].head()

0    38114
1    13053
2    99867
3    13407
4    73765
Name: PLZ, dtype: str

In [54]:
sales_clean['PLZ'].str.len().value_counts()

PLZ
5    436
Name: count, dtype: int64

In [56]:
#BestellNr. zu Text machen
sales_clean['BestellNr.'] = sales_clean['BestellNr.'].astype(str)
sales_clean['BestellNr.'].apply(type).value_counts()

BestellNr.
<class 'str'>    436
Name: count, dtype: int64

In [59]:
#artike und PZN zu Text
sales_clean['Artikel'] = sales_clean['Artikel'].astype(str)
sales_clean['PZN'] = sales_clean['PZN'].astype(str)

In [60]:
sales_clean[['Artikel', 'PZN']].dtypes

Artikel    str
PZN        str
dtype: object

In [61]:
sales_clean[['Versanddatum', 'Empfangszeit']].dtypes

Versanddatum    datetime64[us]
Empfangszeit    datetime64[us]
dtype: object

In [ ]:
################################cleaning inventory#######################################

In [64]:
inventory_clean = df_inventory.copy()

In [66]:
inventory_clean['ArtikelNr'] = inventory_clean['ArtikelNr'].astype(str)

In [67]:
inventory_clean['Charge'] = inventory_clean['Charge'].astype(str)

In [68]:
inventory_clean[['Zugang', 'Abgang', 'Retouren', 'sonstige Vernichtung', 'Inventuren']] = (
    inventory_clean[['Zugang', 'Abgang', 'Retouren', 'sonstige Vernichtung', 'Inventuren']].fillna(0)
)

In [69]:
df_plz['PLZ'] = df_plz['PLZ'].astype(str).str.zfill(5)

In [70]:
#kopie von plz tabelle:
plz_clean = df_plz.copy()

In [71]:
plz_clean['PLZ'] = plz_clean['PLZ'].astype(str).str.zfill(5)

In [72]:
plz_clean['PLZ'].str.len().value_counts()

PLZ
5    8196
Name: count, dtype: int64

In [73]:
#######################merge#######################################
#umsatzstatistik mit PLZ

In [74]:
sales_clean = sales_clean.merge(plz_clean, on='PLZ', how='left')

In [75]:
sales_clean[['PLZ', 'Bundesland', 'Kreis', 'Typ']].head()

     PLZ         Bundesland         Kreis    Typ
0  38114      Niedersachsen  Braunschweig  Stadt
1  13053             Berlin        Berlin  Stadt
2  99867          Thüringen         Gotha  Kreis
3  13407             Berlin        Berlin  Stadt
4  73765  Baden-Württemberg     Esslingen  Kreis

In [76]:
sales_clean.shape

(436, 22)

In [77]:
##cleaning function sales & plz

In [155]:
def clean_sales(df, plz_df):
    df = df.copy()

    df['PLZ'] = df['PLZ'].astype(str).str.zfill(5)
    df['BestellNr.'] = df['BestellNr.'].astype(str)
    df['Artikel'] = df['Artikel'].astype(str)
    df['PZN'] = df['PZN'].astype(str)

    df['Ort'] = df['Ort'].apply(clean_text)
    df['Bezeichnung'] = df['Bezeichnung'].apply(clean_text)

    df['Berichtsmonat'] = df['Versanddatum'].dt.to_period('M').astype(str)

    df = df.merge(plz_df, on='PLZ', how='left')

    return df

In [156]:
sales_test = clean_sales(df_sales, plz_clean)

In [157]:
sales_test.shape

(436, 23)

In [158]:
clean_sales(df_sales, plz_clean)

,Versanddatum,Auftragsart,Qualifier,Beschreibung,Auftrag,Auftraggeber,BestellNr.,Kundengrupp,Name,Strasse,...,PZN,Bezeichnung,Liefermenge,Umsatz,Empfangszeit,Sendung,Berichtsmonat,Bundesland,Kreis,Typ
0,2026-01-02,Normalauftrag,Auftragsposition,Verkauf,615752,2158,3383,Pharma Pri,Richard Kehr GmbH & Co. KG,Sudetenstraﬂe 8,...,7338535,NOBITE Hautspray 100 ml,36,299.52,2025-12-30 12:30:28,9614926,2026-01,Niedersachsen,Braunschweig,Stadt
1,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615885,568211765,56141,ANZAG,Alliance Healthcare Deutschland GmbH Niederlas...,Plauener Str. 161,...,325707,NOBITE Kleidung Spray 100 ml,24,199.68,2026-01-02 10:26:34,9616810,2026-01,Berlin,Berlin,Stadt
2,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615982,2180,91536,PHOENIX,PHOENIX Pharmahandel GmbH & Co. KG Vertriebsze...,Am Kindleber Feld 3,...,7338535,NOBITE Hautspray 100 ml,12,99.84,2026-01-02 12:02:30,9617516,2026-01,Thüringen,Gotha,Kreis
3,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615969,2155,81548,PHOENIX,PHOENIX Pharmahandel GmbH & Co. KG Vertriebsze...,Lengeder Straﬂe 42,...,325707,NOBITE Kleidung Spray 100 ml,12,99.84,2026-01-02 12:01:52,9617495,2026-01,Berlin,Berlin,Stadt
4,2026-01-05,Normalauftrag,Auftragsposition,Verkauf,615862,2227,49965,PHOENIX,PHOENIX Pharmahandel GmbH & Co. KG Vertriebsze...,Schurwaldstraﬂe 14-16,...,325707,NOBITE Kleidung Spray 100 ml,12,99.84,2026-01-02 10:12:14,9616702,2026-01,Baden-Württemberg,Esslingen,Kreis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,2026-01-30,Normalauftrag,Auftragsposition,Verkauf,620050,2192,I51496,Noweda,Ebert & Jacobi GmbH & Co. KG Zweigniederlassun...,Nattheimer Straﬂe 106,...,7338535,NOBITE Hautspray 100 ml,12,99.84,2026-01-29 12:30:11,9727418,2026-01,Baden-Württemberg,Heidenheim,Kreis
432,2026-01-30,Normalauftrag,Auftragsposition,Verkauf,619954,2226,N35000,Noweda,NOWEDA Pharma-Handels-GmbH Auslieferungsdepot...,Am Hochheimer See 11,...,7338535,NOBITE Hautspray 100 ml,12,99.84,2026-01-29 09:40:07,9725245,2026-01,Thüringen,Gotha,Kreis
433,2026-01-30,Normalauftrag,Auftragsposition,Verkauf,619955,2241,R61269,Noweda,NOWEDA GmbH & Co. KG,Apothekerstraﬂe 1,...,4436102,NOBITE Kleidung Sprühflasche 200 ml,12,126.60,2026-01-29 09:40:07,9725249,2026-01,Sachsen,Mittelsachsen,Kreis
434,2026-01-30,Normalauftrag,Auftragsposition,Verkauf,619956,2299,T55695,Noweda,NOWEDA Pharma-Handels-GmbH,Apothekerstraﬂe 1,...,4259189,NOBITE Verdünner Flasche 100ml,36,379.80,2026-01-29 09:40:07,9725253,2026-01,Sachsen,Nordsachsen,Kreis
435,2026-01-30,Normalauftrag,Auftragsposition,Verkauf,619925,2208,506072,Pharma Pri,Max Jenne Arzneimittel-Groﬂhandlung KG Zweigni...,Novgorodstr. 12,...,4436102,NOBITE Kleidung Sprühflasche 200 ml,6,63.30,2026-01-29 09:30:20,9725123,2026-01,Schleswig-Holstein,Lübeck,Stadt

In [159]:
##cleaning function inevntory

In [160]:
def clean_inventory(df):
    df = df.copy()

    df['ArtikelNr'] = df['ArtikelNr'].astype(str)
    df['Charge'] = df['Charge'].astype(str)
    df['Bezeichnung'] = df['Bezeichnung'].apply(clean_text)

    df[['Zugang', 'Abgang', 'Retouren', 'sonstige Vernichtung', 'Inventuren']] = (
        df[['Zugang', 'Abgang', 'Retouren', 'sonstige Vernichtung', 'Inventuren']].fillna(0)
    )

    return df

In [161]:
inventory_test = clean_inventory(df_inventory)

In [162]:
inventory_test.shape

(25, 22)

In [163]:
#testing jan, feb, march 2026: sales

In [164]:
df_sales_jan = pd.read_excel("data/raw/sales_2026/Umsatzstatistik Tropical Concept 31.01.2026.xlsx")
df_sales_feb = pd.read_excel("data/raw/sales_2026/Umsatzstatistik Tropical Concept 28.02.2026.xlsx")
df_sales_mar = pd.read_excel("data/raw/sales_2026/Umsatzstatistik Tropical Concept 31.03.2026.xlsx")

sales_jan_clean = clean_sales(df_sales_jan, plz_clean)
sales_feb_clean = clean_sales(df_sales_feb, plz_clean)
sales_mar_clean = clean_sales(df_sales_mar, plz_clean)

sales_all = pd.concat([sales_jan_clean, sales_feb_clean, sales_mar_clean], ignore_index=True)
sales_all.shape

(1453, 23)

In [165]:
len(sales_jan_clean) + len(sales_feb_clean) + len(sales_mar_clean) == len(sales_all)

True

In [166]:
sales_all['Bundesland'].isna().sum()

np.int64(0)

In [167]:
sales_all['Versanddatum'].min(), sales_all['Versanddatum'].max()

(Timestamp('2026-01-02 00:00:00'), Timestamp('2026-03-31 00:00:00'))

In [168]:
sales_all[['Liefermenge', 'Umsatz']].apply(pd.to_numeric, errors='coerce').isna().sum()

Liefermenge    0
Umsatz         0
dtype: int64

In [169]:
sales_all.duplicated().sum()

np.int64(0)

In [170]:
##Umlaute anschauen:

In [171]:
sales_all[sales_all['Ort'].str.contains(r"['¸,]", regex=True, na=False)]['Ort'].unique()

<ArrowStringArray>
[]
Length: 0, dtype: str

In [172]:
sales_all[sales_all['Bezeichnung'].str.contains(r"[¸',]", regex=True, na=False)]['Bezeichnung'].unique()

<ArrowStringArray>
[]
Length: 0, dtype: str

In [173]:
sales_all[sales_all['Ort'].str.contains(r"[¸ˆ]", regex=True, na=False)]['Ort'].unique()

<ArrowStringArray>
[]
Length: 0, dtype: str

In [174]:
def clean_text(text):
    return text.replace('¸', 'ü').replace('ˆ', 'ö')

In [175]:
sales_all['Ort'] = sales_all['Ort'].apply(clean_text)
sales_all['Bezeichnung'] = sales_all['Bezeichnung'].apply(clean_text)

In [176]:
sales_all[sales_all['Ort'].str.contains(r"[¸ˆ]", regex=True, na=False)]['Ort'].unique()

<ArrowStringArray>
[]
Length: 0, dtype: str

In [177]:
sales_all[sales_all['Bezeichnung'].str.contains(r"[¸ˆ]", regex=True, na=False)]['Bezeichnung'].unique()

<ArrowStringArray>
[]
Length: 0, dtype: str

In [178]:
#testing jan, feb, march 2026: inventory

In [179]:
df_inventory_jan = pd.read_excel("data/raw/inventory_2026/LagerlisteTropical-2026-01-31.xlsx")
df_inventory_feb = pd.read_excel("data/raw/inventory_2026/LagerlisteTropical-2026-02-28.xlsx")
df_inventory_mar = pd.read_excel("data/raw/inventory_2026/LagerlisteTropical-2026-03-31.xlsx")

inventory_jan_clean = clean_inventory(df_inventory_jan)
inventory_feb_clean = clean_inventory(df_inventory_feb)
inventory_mar_clean = clean_inventory(df_inventory_mar)

inventory_jan_clean['Berichtsmonat'] = '2026-01'
inventory_feb_clean['Berichtsmonat'] = '2026-02'
inventory_mar_clean['Berichtsmonat'] = '2026-03'

inventory_all = pd.concat([inventory_jan_clean, inventory_feb_clean, inventory_mar_clean], ignore_index=True) 
inventory_all.shape

(77, 23)

In [180]:
inventory_all.duplicated().sum()

np.int64(0)

In [181]:
abs(inventory_all['Abgang'].sum()), sales_all['Liefermenge'].sum()

(np.float64(96281.0), np.int64(96281))

In [182]:
sales_all.groupby('Berichtsmonat')['Liefermenge'].sum()

Berichtsmonat
2026-01    22559
2026-02    27617
2026-03    46105
Name: Liefermenge, dtype: int64

In [183]:
inventory_all.groupby('Berichtsmonat')['Abgang'].sum().abs()

Berichtsmonat
2026-01    22559.0
2026-02    27617.0
2026-03    46105.0
Name: Abgang, dtype: float64